[package]
name = "chess"
version.workspace = true
edition.workspace = true

[dependencies]
chess-core = { path = "../core" }
chess-agents = { path = "../agents" }
crossterm = "0.27"

[[bin]]
name = "chess"
path = "src/main.rs"